app = "byu-scheduler"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  GIN_MODE = "release"

[[mounts]]
  source = "byu_scheduler_data"
  destination = "/app/data"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "GET"
    path = "/api/health"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
